Fix navbar CSS
NikolasPpd/RaceHunter-Front-End pull request #17
Opened 2023-01-06 13:11 UTC by N10beP

Solves #14

2023-01-06 13:46 UTC, NikolasPpd requested changes
Πολύ ωραίο. Έχω σημειώσει μόνο 2 σημεία για αλλαγές στο padding.

2023-01-06 13:46 UTC, NikolasPpd commented on src/components/Navbar/navbar.css
>  }
```suggestion
```
Αυτό το padding καθορίζει το ύψος του navbar και χαλάει ελαφρώς και τη στοίχιση.
Το ύψος καλό είναι να καθορίζεται από το ίδιο το navbar (βλ. σχόλιο στην CSS του `<header>`.

2023-01-06 13:46 UTC, NikolasPpd commented on src/components/Navbar/navbar.css
> +    padding: 10px 30px;
```suggestion
    padding: 16px 30px;
```
Μια τιμή για το vertical padding κοντά στα 16px νομίζω είναι καλή.

2023-01-06 14:20 UTC, NikolasPpd requested changes
Ενώ αφαίρεσες το padding του κουμπιού <kbd>Σύνδεση</kbd> από το `navbar.css`, φαίνεται να υπάρχει ακριβώς το ίδιο CSS rule στο αρχείο `styles.css` στις γραμμές 46-48 οπότε θα πρέπει να αφαιρεθεί και από εκεί για να υπάρξει αλλαγή στην εμφάνιση.

2023-01-06 17:08 UTC, NikolasPpd approved these changes

2023-01-21 08:31 UTC, lnesh approved these changes

2023-01-21 08:31 UTC, merged