Create About Us page
NikolasPpd/RaceHunter-Front-End pull request #24
Opened 2023-01-13 17:43 UTC by N10beP

Solves #8 
Στο προηγούμενο PR έγινε λάθος με το branch και έπρεπε να το κάνω rebase, οπότε αγνοήστε το.

2023-01-13 18:55 UTC, NikolasPpd requested changes
Ωραίο. Τα κείμενα θα τα αλλάξουμε όταν αποφασίσουμε τι θα γράφουν.

2023-01-13 18:55 UTC, NikolasPpd commented on src/pages/AboutUsPage/about-us-page.css
> +    /* position: absolute; */
```suggestion
```

2023-01-13 18:55 UTC, NikolasPpd commented on src/pages/AboutUsPage/about-us-page.css
> +    top: 250px;
```suggestion
    top: 215px;
```

2023-01-13 21:31 UTC, NikolasPpd approved these changes

2023-01-21 08:33 UTC, lnesh approved these changes

2023-01-21 08:35 UTC, merged