Added responsive vars to the root
NikolasPpd/RaceHunter-Front-End pull request #30
Opened 2023-03-13 19:53 UTC by Panos-Stergioulas-Mpolis

Εβαλα παραπάνω μεταβλητές στην root της styles.css. Ουσιαστικά τα Normal sizes είναι για laptops τα Mid για tablets και τα small για Κινητά. #20

2023-03-13 21:09 UTC, NikolasPpd submitted a review, later dismissed
Υπάρχει περίπτωση όταν γίνει merge το branch να κλείσει το issue, οπότε και θα το ανοίξω και πάλι γιατί χρειάζονται αρκετές προσθήκες σε CSS για να γίνουν όλα responsive.

2023-03-15 19:17 UTC, lnesh requested changes
Ιδανικά, πρόσθεσε κι ένα var bigger, το οποίο θα αφορά μεγάλους τίτλους (βλ. homepage, about us page). Ενδεικτικά, μπορεί να καθοριστεί τιμή 80px για laptop, 60px για tablet και 50px για μικρότερες συσκευές. Επίσης, ίσως να συγχωνεύαμε mid και small;

2023-03-17 18:18 UTC, NikolasPpd requested changes

2023-03-17 18:18 UTC, NikolasPpd commented on src/assets/styles.css
> +    --Small-mid-text-size: 9px;
Αυτά τα 2 (ίσως και το small-big-text-size από πάνω νομίζω παραμένουν πολύ μικρά για να διαβάζονται, ιδίως σε mobile

2023-03-17 18:22 UTC, Panos-Stergioulas-Mpolis commented on src/assets/styles.css
> +    --Small-mid-text-size: 9px;
Είναι τα ψιλά γράμματα που λέμε. Μπορεί να μπούν στους όρους χρήσης.

2023-03-17 18:26 UTC, Panos-Stergioulas-Mpolis commented on src/assets/styles.css
> +    --Small-mid-text-size: 9px;
Επίσης το να έχουμε κάτι παραπάνω για τώρα δεν πειράζει.
Αν δεν μας χρειαστεί θα το βγάλουμε στην συνέχεια.

2023-03-17 18:34 UTC, merged